name: 'Install VapourSynth'
description: 'Install the VapourSynth C++ library in the current runner'
inputs:
  version:
    description: 'Version to install'
    required: true
  zimg-version:
    description: 'Override the automated zimg version that will be installed'
    required: false
    default: 0
  cache:
    description: 'Cache the compiled library'
    required: false
    default: true
outputs:
  zimg-branch:
    description: "Version of zimg that was compiled"
    value: ${{ steps.get-zimg-branch.outputs.zimg-branch }}
runs:
  using: 'composite'
  steps:
    - name: Ensure NASM is installed
      run: sudo apt-get install --yes nasm
      shell: bash

    - name: Get zimg branch
      id: get-zimg-branch
      run: |
        explicit_version=${{ inputs.zimg-version }}
        if [ $explicit_version -gt 0 ]; then
          branch=$explicit_version
        else
          version=${{ inputs.version }}
          version_int=${version%.*}
          if [ $version_int -ge 55 ]; then
            branch=3.0
          elif [ $version_int -ge 46 ]; then
            branch=2.9
          elif [ $version_int -ge 45 ]; then
            branch=2.8
          else
            branch=2.7
          fi
        fi
        echo "zimg-branch=$branch" >> $GITHUB_OUTPUT
      shell: bash

    - name: Cache zimg compilation
      if: inputs.cache == 'true'
      id: get-zimg-cache
      uses: actions/cache@v3
      with:
        key: zimg-${{ steps.get-zimg-branch.outputs.zimg-branch }}
        path: /tmp/zimg
    - name: Compile zimg v${{ steps.get-zimg-branch.outputs.zimg-branch }}
      if: inputs.cache == 'false' || steps.get-zimg-cache.outputs.cache-hit != 'true'
      run: |
        branch="v${{ steps.get-zimg-branch.outputs.zimg-branch }}"
        git clone https://github.com/sekrit-twc/zimg --depth 1 --branch $branch /tmp/zimg
        cd /tmp/zimg
        ./autogen.sh
        ./configure --prefix=/usr
        make -j2
      shell: bash
    - name: Install zimg v${{ steps.get-zimg-branch.outputs.zimg-branch }}
      run: |
        cd /tmp/zimg
        sudo make install -j2
      shell: bash

    - name: Cache VapourSynth compilation
      if: inputs.cache == 'true'
      id: get-vs-cache
      uses: actions/cache@v3
      with:
        key: vs-R${{ inputs.version }}
        path: /tmp/vapoursynth
    - name: Compile VapourSynth R${{ inputs.version }}
      if: inputs.cache == 'false' || steps.get-vs-cache.outputs.cache-hit != 'true'
      run: |
        branch="R${{ inputs.version }}"
        git clone https://github.com/vapoursynth/vapoursynth --depth 1 --branch $branch /tmp/vapoursynth
        cd /tmp/vapoursynth
        ./autogen.sh
        ./configure --prefix=/usr --disable-vsscript --disable-python-module
        make -j2
      shell: bash
    - name: Install VapourSynth R${{ inputs.version }}
      run: |
        cd /tmp/vapoursynth
        sudo make install -j2
        pip install .
      shell: bash
